trigger:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: templates
      type: git
      name: Plumbing/core-templates
    - repository: RemoveSoundflower
      type: git
      name: Open/RemoveSoundflower

stages:
- template: stages/sync/azure-sync.yml@templates  # Template reference
  parameters:
    checkout: RemoveSoundflower
